# .aspect/workflows/config.yaml

tasks:
  - ci:
      run_tasks: 
        - build
        - test

  - build:
      targets:
        - "//packages/hello-world:devserver"
  
  - test:
      targets:
        - "//packages/hello-world/..."