# .aspect/workflows/config.yaml

extensions:
  package-json-scripts:
    enabled: false
  rules_shell:
    enabled: false

tasks:
  - build:
      name: "Build DevServer"
      targets:
        - "//packages/hello-world:devserver"
  
  - test:
      name: "Test Hello World"
      targets:
        - "//packages/hello-world/..."
