# .aspect/workflows/config.yaml

tasks:
  - build:
      name: "Build DevServer"
      targets:
        - "//packages/hello-world:devserver"
  
  - test:
      name: "Test Hello World"
      targets:
        - "//packages/hello-world/..."
