# .aspect/workflows/config.yaml
# Estrutura simplificada para evitar o bug de parsing do rosetta 5.14.21.

tasks:
  - checkout:
      update_strategy: rebase
  - test:
      id: test
      # Targets para rodar todos os testes no pacote hello-world
      targets:
        - //packages/hello-world:devserver_test
