# .aspect/workflows/config.yaml

# Manter a configuração mais simples possível para evitar o bug de parsing do rosetta.

tasks:
  - build:
      # Targets para o build do seu devserver
      targets:
        - "//packages/hello-world:devserver"