# .aspect/workflows/config.yaml

# Desativa a extensão que está causando o TypeError durante o parsing do rosetta.
# Esta extensão tenta analisar scripts de package.json, o que é complexo
# e não é estritamente necessário para rodar as tasks 'build' e 'test' principais.
extensions:
  package-json-scripts:
    enabled: false

tasks:
  - ci:
      run_tasks: 
        - build
        - test

  - build:
      targets:
        - "//packages/hello-world:devserver"
  
  - test:
      targets:
        - "//packages/hello-world/..."