# .aspect/workflows/config.yaml
# Consulte o guia de Configuração para o conteúdo típico.
# Para warming, você precisará adicionar 'warming:' em 'tasks:'.

tasks:
  # Você pode adicionar outras tarefas, como 'format:', 'lint:', etc.
  # Se estiver configurando 'warming', adicione:
  # - warming: