configure:
  languages:
    javascript: true
  plugins:
    - .aspect/cli/package-json-scripts.star
lint:
  aspects:
    - //packages/hello-world:devserver

plugins:
    - name: fix-visibility
      from: github.com/aspect-build/plugin-fix-visibility
      version: v0.1.0
