# .aspect/workflows/config.yaml

tasks:
  - build:
      # O campo 'targets' lista os alvos (labels) do Bazel que o Workflows
      # deve construir quando a tarefa 'build' for executada.
      targets:
        - "//packages/hello-world:devserver"