# .circleci/config.yaml
# Using orbs for reusable CircleCI configuration

version: 2.1

orbs:
  workflows: aspect-build/workflows@5.8.18

workflows:
  bazel_ci_workflow:
    jobs:
      - workflows/aspect-workflows:

          resource-class: writechoiceorg/aspect-default 
          filters:
            branches:
              only:
                - main
            tags:
              ignore: /.*/