# .circleci/config.yaml
version: 2.1

jobs:
  aspect-workflows-setup:
    machine:
      image: ubuntu-2204:2023.10.1 
    
    # Resource class must be correct: writechoiceorg/aspect-default
    resource_class: writechoiceorg/aspect-default 
    
    steps:
      - checkout
      - run:
          name: "Setup Aspect Workflows and Continue"
          command: |
            rosetta steps | circleci pipeline continue -c - --job aspect-workflows-setup

workflows:
  build-and-test:
    jobs:
      - aspect-workflows-setup